### ISSUE TITLE
G4 Instant Camera Error in Log

### ISSUE THREAD

**Issue by alaub81** [seaside1/unifiprotect#18]
When I update the snapshot image from my Unify Protect G4 Instant I get the following error in the log file:

```
2023-12-19 08:09:54.824 [ERROR] [nal.common.AbstractInvocationHandler] - An error occurred while calling method 'ThingHandler.handleCommand()' on 'org.openhab.binding.unifiprotect.internal.thing.UniFiProtectG4CameraThingHandler@6519d36d': No enum constant org.openhab.binding.unifiprotect.internal.UniFiProtectRecordingMode.SCHEDULE
java.lang.IllegalArgumentException: No enum constant org.openhab.binding.unifiprotect.internal.UniFiProtectRecordingMode.SCHEDULE
	at java.lang.Enum.valueOf(Enum.java:273) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.UniFiProtectRecordingMode.valueOf(UniFiProtectRecordingMode.java:1) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectBaseThingHandler.refreshChannel(UniFiProtectBaseThingHandler.java:169) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectG4CameraThingHandler.refreshChannel(UniFiProtectG4CameraThingHandler.java:82) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectBaseThingHandler.refresh(UniFiProtectBaseThingHandler.java:105) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectG4CameraThingHandler.refresh(UniFiProtectG4CameraThingHandler.java:71) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectBaseThingHandler.handleSnapshot(UniFiProtectBaseThingHandler.java:432) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectBaseThingHandler.handleCommand(UniFiProtectBaseThingHandler.java:372) ~[?:?]
	at org.openhab.binding.unifiprotect.internal.thing.UniFiProtectG4CameraThingHandler.handleCommand(UniFiProtectG4CameraThingHandler.java:88) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor163.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.InvocationHandlerSync.invoke(InvocationHandlerSync.java:59) [bundleFile:?]
	at jdk.proxy176427.$Proxy176611.handleCommand(Unknown Source) [?:?]
	at org.openhab.core.thing.internal.profiles.ProfileCallbackImpl.handleCommand(ProfileCallbackImpl.java:94) [bundleFile:?]
	at org.openhab.core.thing.internal.profiles.SystemDefaultProfile.onCommandFromItem(SystemDefaultProfile.java:48) [bundleFile:?]
	at jdk.internal.reflect.GeneratedMethodAccessor224.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.openhab.core.internal.common.AbstractInvocationHandler.invokeDirect(AbstractInvocationHandler.java:147) [bundleFile:?]
	at org.openhab.core.internal.common.Invocation.call(Invocation.java:52) [bundleFile:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
The Snapshot is updating, so only problem is that the log file gets these errors. My G3 Instant Cameras are working well and there is no entry in the log file while updating the snapshot.

I am on the latest release of the binding: 4.0.0.202311251106 
And also on the latest stable protect version: 2.10.11

If you have any questions, just ask me.

cheers
Andreas

**Comment by seaside1** [comment]
Sorry for late feedback I will have a look.
I don't have a G4 instant myself, what would help is if you can send me the boostrap.log
If you enable debug for the binding it will store it on your filesystem (and print where in the logs).
You can send the log to me sealside@gmail.com or PM me on openhab forums with the log.

**Comment by alaub81** [comment]
I am sorry, but I uninstalled the binding, because it was to unstable. If you like, I can try it again in a few weeks and send the logs.

**Comment by seaside1** [comment]
I'll close this issue. If you want to try G4 Instant support you can reopen and send med the bootstrap.
